build_archive_repo = "ZMyApps/build-archive"
ipa_archive_repo = "ZMyApps/ipa-archive"
tweak_archive_repo = "ZMyApps/tweak-archive"

[[apps]]
name = "Apollo"
bundle_identifier = "com.christianselig.Apollo"

[[apps]]
name = "Facebook"
bundle_identifier = "com.facebook.Facebook"

[[apps]]
name = "Infuse"
bundle_identifier = "com.firecore.infuse"

[[apps]]
name = "Instagram"
bundle_identifier = "com.burbn.instagram"

[[apps]]
name = "TikTok"
bundle_identifier = "com.zhiliaoapp.musically"

# [[apps]]
# name = "TikTokGlobal"
# bundle_identifier = "com.ss.iphone.ugc.Ame"

[[apps]]
name = "X"
bundle_identifier = "com.atebits.Tweetie2"

[[apps]]
name = "YouTube"
bundle_identifier = "com.google.ios.youtube"

[[apps]]
name = "YouTubeMusic"
bundle_identifier = "com.google.ios.youtubemusic"
