workspace_repo = "ZMyApps/workspace"
build_archive_repo = "ZMyApps/build-archive"
ipa_archive_repo = "ZMyApps/ipa-archive"
tweak_archive_repo = "ZMyApps/tweak-archive"

[[apps]]
name = "Apollo"
bundle_identifier = "com.christianselig.Apollo"

[[tweaks]]
name = "ApolloICA"
app_name = "Apollo"

[[tweaks.debs]]
method = "github_release_latest"
repo = "JeffreyCA/Apollo-ImprovedCustomApi"
endswith = "rootless.deb"
use_version = true

#####################################################

[[apps]]
name = "Facebook"
bundle_identifier = "com.facebook.Facebook"

[[tweaks]]
name = "FacebookGlow"
app_name = "Facebook"

[[tweaks.deb]]
method = "github_release_latest"
repo = "dayanch96/Glow"
endswith = "arm64.deb"
use_version = true

#####################################################

[[apps]]
name = "Infuse"
bundle_identifier = "com.firecore.infuse"

[[tweaks]]
name = "InfusePlus"
app_name = "Infuse"

[[tweaks.deb]]
method = "github_release_latest"
repo = "dayanch96/InfusePlus"
endswith = "arm64.deb"
use_version = true

#####################################################

[[apps]]
name = "Instagram"
bundle_identifier = "com.burbn.instagram"

[[tweaks]]
name = "SCInsta"
app_name = "Instagram"

[[tweaks.deb]]
method = "github_release_latest"
repo = "SoCuul/SCInsta"
endswith = "rootless.deb"
use_version = true

[[tweaks]]
name = "RyukGram"
app_name = "Instagram"

[[tweaks.deb]]
method = "github_release_latest"
repo = "faroukbmiled/RyukGram"
endswith = "rootless.deb"
use_version = true

#####################################################

[[apps]]
name = "TikTok"
bundle_identifier = "com.zhiliaoapp.musically"

# [[apps]]
# name = "TikTokGlobal"
# bundle_identifier = "com.ss.iphone.ugc.Ame"

#####################################################

[[apps]]
name = "X"
bundle_identifier = "com.atebits.Tweetie2"

[[tweaks]]
name = "BHTwitter"
app_name = "X"

[[tweaks.deb]]
method = "github_release_latest"
repo = "BandarHL/BHTwitter"
endswith = "arm64.deb"
use_version = true

#####################################################

[[apps]]
name = "YouTube"
bundle_identifier = "com.google.ios.youtube"

[[tweaks]]
name = "YouMod"
app_name = "YouTube"

[[tweaks.debs]]
method = "github_release_latest"
repo = "Tonwalter888/YouMod"
endswith = "arm64.deb"
use_version = true

[[tweaks.debs]]
method = "cydia_repo_latest"
repo = "https://poomsmart.github.io/repo"
package = "com.ps.ytvideooverlay"
architecture = "iphoneos-arm64"

[[tweaks.debs]]
method = "cydia_repo_latest"
repo = "https://poomsmart.github.io/repo"
package = "com.ps.youpip"
architecture = "iphoneos-arm64"

[[tweaks]]
name = "ZMyYouTube"
app_name = "YouTube"

[[tweaks.debs]]
method = "cydia_repo_latest"
repo = "https://poomsmart.github.io/repo"
package = "com.ps.ytabgoodies"
architecture = "iphoneos-arm64"

[[tweaks.debs]]
method = "cydia_repo_latest"
repo = "https://poomsmart.github.io/repo"
package = "com.ps.ytx"
architecture = "iphoneos-arm64"

[[tweaks.debs]]
method = "cydia_repo_latest"
repo = "https://poomsmart.github.io/repo"
package = "com.ps.ytvideooverlay"
architecture = "iphoneos-arm64"

[[tweaks.debs]]
method = "cydia_repo_latest"
repo = "https://poomsmart.github.io/repo"
package = "com.ps.youpip"
architecture = "iphoneos-arm64"

[[tweaks.debs]]
method = "github_release_version"
repo = "hbang/Alderis"
version = "1.2.3"
endswith = "arm64.deb"

[[tweaks.debs]]
method = "cydia_repo_latest"
repo = "https://repo.icrazeios.com"
package = "com.galacticdev.isponsorblock"
architecture = "iphoneos-arm64"

#####################################################

[[apps]]
name = "YouTubeMusic"
bundle_identifier = "com.google.ios.youtubemusic"

[[tweaks]]
name = "YTMusicUltimate"
app_name = "YouTubeMusic"

[[tweaks.deb]]
method = "github_release_latest"
repo = "dayanch96/YTMusicUltimate"
endswith = "arm64.deb"
use_version = true
